pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot-preview[bot]
      - status-success=ngstack.electron
    actions:
      merge:
        method: merge
